[project]
name = "recipe-api"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "django>=5.2",
    "djangorestframework",
    "django-filter",
    "django-cors-headers",
    "django-allauth",
    "dj-rest-auth",
    "djangorestframework-simplejwt",
    "drf-spectacular",
    "django-environ",
    "psycopg[binary]",
    "pillow",
]

[dependency-groups]
dev = [
    "ruff",
    "basedpyright",
    "pytest",
    "pytest-django",
    "factory-boy",
    "coverage",
    "django-extensions",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py", "*_test.py", "*_access.py"]

[tool.ruff]
line-length = 100
target-version = "py313"
extend-exclude = ["*/migrations/*.py"]

[tool.ruff.lint]
select = ["E","F","I","UP","DJ"]

[tool.basedpyright]
typeCheckingMode = "standard"
exclude = ["**/migrations/*.py", ".venv"]

reportMissingTypeStubs = "none"
reportUnusedCallResult = "none"
reportImplicitStringConcatenation = "none"
reportUnknownVariableType = "none"
reportAny = "none"
