# Generated by Django 6.0.7 on 2026-07-22 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbooks', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cookbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plannings', to='cookbooks.cookbook')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plannings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePlanning',
            fields=[
                ('pk', models.CompositePrimaryKey('recipe', 'planning', blank=True, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=50)),
                ('dayofweek', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_plannings', to='planning.planning')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_plannings', to='recipes.recipe')),
            ],
        ),
    ]
