# Generated by Django 6.0.7 on 2026-07-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('recipes', '0003_recipe_cooking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeplanning',
            name='pk',
        ),
        # RemoveField above only updates Django's model state - the composite
        # PRIMARY KEY constraint itself is still on the table, and Postgres
        # won't allow adding the new `id` PRIMARY KEY column while it exists.
        migrations.RunSQL(
            sql='ALTER TABLE "planning_recipeplanning" DROP CONSTRAINT "planning_recipeplanning_pkey";',
            reverse_sql=(
                'ALTER TABLE "planning_recipeplanning" '
                'ADD CONSTRAINT "planning_recipeplanning_pkey" PRIMARY KEY (recipe_id, planning_id);'
            ),
        ),
        migrations.AddField(
            model_name='recipeplanning',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='recipeplanning',
            constraint=models.UniqueConstraint(fields=('planning', 'dayofweek', 'lunch', 'type'), name='unique_recipe_planning_slot'),
        ),
    ]
