# Generated by Django 6.0.7 on 2026-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_recipeplanning_surrogate_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='icon',
            field=models.TextField(blank=True, default='data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iIzNCNkU4RiI+PHBhdGggZD0iTTcgMnYySDVhMiAyIDAgMCAwLTIgMnYxNGEyIDIgMCAwIDAgMiAyaDE0YTIgMiAwIDAgMCAyLTJWNmEyIDIgMCAwIDAtMi0yaC0yVjJoLTJ2Mkg5VjJIN3pNNSA5aDE0djExSDVWOXoiLz48L3N2Zz4=', null=True),
        ),
    ]
