# Generated by Django 6.0.7 on 2026-08-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_planning_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='type',
            field=models.CharField(choices=[('journalier', 'Journalier'), ('hebdomadaire', 'Hebdomadaire')], default='hebdomadaire', max_length=20),
        ),
    ]
