# Generated by Django 6.0.7 on 2026-07-22 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cookbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedUserCookbook',
            fields=[
                ('pk', models.CompositePrimaryKey('cookbook', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_with', to='cookbooks.cookbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_cookbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
