# Generated by Django 6.0.7 on 2026-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedusercookbook',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('editor', 'Editor'), ('commentator', 'Commentator'), ('reader', 'Reader')], max_length=50),
        ),
    ]
