# Generated by Django 6.0.7 on 2026-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbooks', '0002_alter_sharedusercookbook_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='icon',
            field=models.TextField(blank=True, default='data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iIzZCNEYzQiI+PHBhdGggZD0iTTEyIDRDMTAgMi41IDYgMiAzIDN2MTVjMy0xIDctLjUgOSAxIDItMS41IDYtMiA5LTFWM2MtMy0xLTctLjUtOSAxeiIvPjwvc3ZnPg==', null=True),
        ),
    ]
