# Generated by Django 6.0.7 on 2026-07-22 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbooks', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('canal', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='cookbooks.cookbook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='recipes.recipe')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
