# Generated by Django 6.0.7 on 2026-07-26 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('recipes', '0004_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='recipes.recipe'),
        ),
    ]
