# Generated by Django 6.0.7 on 2026-08-06 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbooks', '0003_cookbook_icon'),
        ('messaging', '0002_alter_message_recipe'),
        ('planning', '0004_planning_type'),
        ('recipes', '0004_favoriterecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='planning.planning'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('recipe__isnull', False), ('planning__isnull', False), _negated=True), name='message_not_both_recipe_and_planning'),
        ),
    ]
