CREATE TABLE IF NOT EXISTS "cookbook" (
	"id" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"creator_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "recipe" (
	"id" INTEGER NOT NULL,
	"title" TEXT NOT NULL,
	"image" TEXT,
	"source" TEXT,
	"cooking_duration" NUMERIC,
	"creator_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"cookbook_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "user" (
	"id" INTEGER NOT NULL,
	"firstname" TEXT NOT NULL,
	"lastname" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"profile_icon" TEXT NOT NULL,
	"password" TEXT NOT NULL,
	"email" TEXT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "tag" (
	"id" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	"type" TEXT NOT NULL,
	"description" TEXT,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "recipe_tag" (
	"recipe_id" INTEGER NOT NULL,
	"tag_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("recipe_id", "tag_id")
);




CREATE TABLE IF NOT EXISTS "ingredient" (
	"id" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	"image" TEXT,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "recipe_ingredient" (
	"recipe_id" INTEGER NOT NULL,
	"ingredient_id" INTEGER NOT NULL,
	"quantity" NUMERIC NOT NULL,
	"unity" TEXT,
	"person_numbers" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("recipe_id", "ingredient_id")
);




CREATE TABLE IF NOT EXISTS "OAuth_user" (
	"id" INTEGER NOT NULL,
	"provider" TEXT NOT NULL,
	"provider_url" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"profile_icon" TEXT,
	"user_id" INTEGER NOT NULL,
	"domain" TEXT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "shared_user_cookbook" (
	"cookbook_id" INTEGER NOT NULL,
	"user_id" INTEGER NOT NULL,
	"role" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("cookbook_id", "user_id")
);




CREATE TABLE IF NOT EXISTS "message" (
	"id" INTEGER NOT NULL,
	"content" TEXT NOT NULL,
	"author_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"canal" TEXT NOT NULL,
	"cookbook_id" INTEGER NOT NULL,
	"recipe_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "step" (
	"id" INTEGER NOT NULL,
	"description" TEXT NOT NULL,
	"step_number" INTEGER NOT NULL,
	"dury" TIMESTAMP NOT NULL,
	"type" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"recipe_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "planning" (
	"id" INTEGER NOT NULL,
	"name" TEXT NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"creator_id" INTEGER NOT NULL,
	"cookbook_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "recipe_planning" (
	"recipe_id" INTEGER NOT NULL,
	"planning_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	"type" TEXT NOT NULL,
	"lunch" TEXT NOT NULL,
	"dayofweek" TEXT,
	PRIMARY KEY("recipe_id", "planning_id")
);




CREATE TABLE IF NOT EXISTS "user_preferences" (
	"user_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"tag_id" INTEGER NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("user_id", "tag_id")
);



ALTER TABLE "recipe_ingredient"
ADD FOREIGN KEY("ingredient_id") REFERENCES "ingredient"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe_ingredient"
ADD FOREIGN KEY("recipe_id") REFERENCES "recipe"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "message"
ADD FOREIGN KEY("cookbook_id") REFERENCES "cookbook"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "cookbook"
ADD FOREIGN KEY("creator_id") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "OAuth_user"
ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "shared_user_cookbook"
ADD FOREIGN KEY("cookbook_id") REFERENCES "cookbook"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "shared_user_cookbook"
ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe"
ADD FOREIGN KEY("creator_id") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe_tag"
ADD FOREIGN KEY("recipe_id") REFERENCES "recipe"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe_tag"
ADD FOREIGN KEY("tag_id") REFERENCES "tag"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "step"
ADD FOREIGN KEY("recipe_id") REFERENCES "recipe"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe_planning"
ADD FOREIGN KEY("planning_id") REFERENCES "planning"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe_planning"
ADD FOREIGN KEY("recipe_id") REFERENCES "recipe"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "planning"
ADD FOREIGN KEY("cookbook_id") REFERENCES "cookbook"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "recipe"
ADD FOREIGN KEY("cookbook_id") REFERENCES "cookbook"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "planning"
ADD FOREIGN KEY("creator_id") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "message"
ADD FOREIGN KEY("author_id") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "message"
ADD FOREIGN KEY("recipe_id") REFERENCES "recipe"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_preferences"
ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_preferences"
ADD FOREIGN KEY("tag_id") REFERENCES "tag"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
