# Generated by Django 6.0.7 on 2026-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
