# Generated by Django 6.0.7 on 2026-07-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.TextField(blank=True, default=''),
        ),
    ]
